services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    build: db
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
